use crate::error::ArchiveError;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::fs::File;
use std::path::Path;

/// A node in the historical knowledge graph (e.g., a Person or Place)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KgNode {
    pub id: String,
    // NetworkX stores attributes loosely, but we know 'id' is the name.
}

/// An edge representing a co-occurrence or relationship
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KgEdge {
    pub source: String,
    pub target: String,
    pub weight: usize,
}

/// Raw representation of the NetworkX JSON export
#[derive(Debug, Clone, Deserialize)]
struct NetworkXGraph {
    nodes: Vec<KgNode>,
    links: Vec<KgEdge>,
}

/// A structured graph for fast querying
#[derive(Debug, Clone)]
pub struct KnowledgeGraph {
    pub nodes: HashMap<String, KgNode>,
    /// Adjacency list: node_id -> Vec<KgEdge>
    pub edges: HashMap<String, Vec<KgEdge>>,
}

impl KnowledgeGraph {
    /// Load the graph from the JSON generated by the spaCy pipeline
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self, ArchiveError> {
        let file = File::open(path).map_err(|e| ArchiveError::Malformed(e.to_string()))?;
        let nx_graph: NetworkXGraph = serde_json::from_reader(file).map_err(ArchiveError::Json)?;
        Self::from_networkx(nx_graph)
    }

    /// Load the graph from a JSON slice (useful for WASM)
    pub fn load_from_slice(data: &[u8]) -> Result<Self, ArchiveError> {
        let nx_graph: NetworkXGraph = serde_json::from_slice(data).map_err(ArchiveError::Json)?;
        Self::from_networkx(nx_graph)
    }

    fn from_networkx(nx_graph: NetworkXGraph) -> Result<Self, ArchiveError> {
        let mut nodes = HashMap::new();
        for node in nx_graph.nodes {
            nodes.insert(node.id.clone(), node);
        }

        let mut edges: HashMap<String, Vec<KgEdge>> = HashMap::new();
        for link in nx_graph.links {
            // Undirected graph, so add edge to both source and target
            edges
                .entry(link.source.clone())
                .or_default()
                .push(link.clone());

            let reverse_link = KgEdge {
                source: link.target.clone(),
                target: link.source.clone(),
                weight: link.weight,
            };
            edges
                .entry(link.target.clone())
                .or_default()
                .push(reverse_link);
        }

        Ok(Self { nodes, edges })
    }

    /// Get all direct connections for a specific entity, sorted by weight (strongest first)
    pub fn connections_for(&self, entity_id: &str, limit: usize) -> Vec<KgEdge> {
        let mut conns = self.edges.get(entity_id).cloned().unwrap_or_default();
        conns.sort_by(|a, b| b.weight.cmp(&a.weight));
        conns.into_iter().take(limit).collect()
    }

    /// Extract a localized subgraph around a focal entity (e.g., 2 degrees of separation)
    pub fn ego_graph(
        &self,
        focal_entity: &str,
        depth: usize,
        max_nodes: usize,
    ) -> (Vec<KgNode>, Vec<KgEdge>) {
        if !self.nodes.contains_key(focal_entity) {
            return (vec![], vec![]);
        }

        let mut visited_nodes = HashSet::new();
        let mut current_frontier = vec![focal_entity.to_string()];
        visited_nodes.insert(focal_entity.to_string());

        let mut subgraph_edges = Vec::new();

        for _ in 0..depth {
            if visited_nodes.len() >= max_nodes {
                break;
            }
            let mut next_frontier = Vec::new();
            for node_id in current_frontier {
                if let Some(neighbors) = self.edges.get(&node_id) {
                    for edge in neighbors {
                        // Avoid duplicates in the edge list
                        if edge.source < edge.target {
                            subgraph_edges.push(edge.clone());
                        }

                        if !visited_nodes.contains(&edge.target) && visited_nodes.len() < max_nodes
                        {
                            visited_nodes.insert(edge.target.clone());
                            next_frontier.push(edge.target.clone());
                        }
                    }
                }
            }
            current_frontier = next_frontier;
        }

        let subgraph_nodes = visited_nodes
            .into_iter()
            .filter_map(|id| self.nodes.get(&id).cloned())
            .collect();

        // Deduplicate edges
        subgraph_edges.sort_by(|a, b| {
            let key_a = (&a.source, &a.target);
            let key_b = (&b.source, &b.target);
            key_a.cmp(&key_b)
        });
        subgraph_edges.dedup_by(|a, b| a.source == b.source && a.target == b.target);

        (subgraph_nodes, subgraph_edges)
    }

    /// Find the shortest path between two entities using BFS
    pub fn shortest_path(&self, start: &str, end: &str) -> Option<Vec<String>> {
        if !self.nodes.contains_key(start) || !self.nodes.contains_key(end) {
            return None;
        }

        let mut queue = std::collections::VecDeque::new();
        let mut visited = HashSet::new();
        let mut parent_map: HashMap<String, String> = HashMap::new();

        queue.push_back(start.to_string());
        visited.insert(start.to_string());

        while let Some(current) = queue.pop_front() {
            if current == end {
                let mut path = vec![end.to_string()];
                let mut curr = end.to_string();
                while let Some(parent) = parent_map.get(&curr) {
                    path.push(parent.clone());
                    curr = parent.clone();
                }
                path.reverse();
                return Some(path);
            }

            if let Some(neighbors) = self.edges.get(&current) {
                for edge in neighbors {
                    if !visited.contains(&edge.target) {
                        visited.insert(edge.target.clone());
                        parent_map.insert(edge.target.clone(), current.clone());
                        queue.push_back(edge.target.clone());
                    }
                }
            }
        }
        None
    }
}
