//! Build-time discovery of `content/blog/*.md` files.
//!
//! Scans the repo-relative `content/blog/` directory, emits a generated
//! Rust source file with each post's markdown bytes plus the directory
//! listing. The main binary `include!`s the generated file so a new post
//! is picked up with a `cargo build` — no source edits required.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let blog_dir = manifest_dir.join("../../content/blog");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("blog_manifest.rs");

    println!("cargo:rerun-if-changed={}", blog_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if blog_dir.exists() {
        if let Ok(read_dir) = fs::read_dir(&blog_dir) {
            for entry in read_dir.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("md") {
                    let name = path
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("")
                        .to_string();
                    if !name.is_empty() {
                        // Make the build re-run if the file changes
                        println!("cargo:rerun-if-changed={}", path.display());
                        entries.push((name, path));
                    }
                }
            }
        }
    }

    // Sort for stable output ordering
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
    src.push_str("pub fn blog_post_sources() -> &'static [(&'static str, &'static str)] {\n");
    src.push_str("    &[\n");
    for (slug, path) in &entries {
        let abs = path.canonicalize().unwrap_or_else(|_| path.clone());
        src.push_str(&format!(
            "        ({:?}, include_str!({:?})),\n",
            slug,
            abs.display().to_string()
        ));
    }
    src.push_str("    ]\n}\n");

    fs::write(&out_path, src).expect("write generated blog manifest");

    // Also touch the directory so removal of a post triggers rebuilds
    println!("cargo:rerun-if-changed=build.rs");
    let _ = Path::new(&blog_dir);
}
